# Generated by Django 5.1.4 on 2025-03-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=11, verbose_name='Локация')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('email_info', models.EmailField(max_length=254, verbose_name='Инфо почта')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Поддержка',
                'verbose_name_plural': 'Поддержка',
            },
        ),
    ]
